### PR TITLE
Feature/fix autofac tests

### PR DESCRIPTION
**Pull request by mareklinka**
This branch fixes the failing Autofac tests.
The issue with those tests is broken type resolution in ReSharper SSR - for some reason, what apparently worked in the earlier version is broken now and has been broken for some time.

The issue was reported: https://youtrack.jetbrains.com/issue/RSRP-458297

I resolved the issue by removing the type requirement from the SSR pattern. I introduced a comment to explain the issue and linked the YouTrack issue as well.

### CODE REVIEW

**Comment by pavolbelusko** [comment]
After discussion with Marek, we decided to keep this pull request open (or eventually abandon it) as the type resolution works in deployed plugin and only doesn't work in unit tests.

**Comment by mareklinka** [comment]
I'm actually thinking this should be scrapped entirely, including the branch, Apparently the type resolution doesn't work properly under test. There is still no official word from JetBrains.

**Comment by pavolbelusko** [comment]
Do we have any update on the Jetbrains issue?

**Comment by mareklinka** [comment]
Closing this thing. Will open a new PR with a proper fix soon.

**Pull request closed without merging**
