### PR TITLE
Fix test setup

### PR DESCRIPTION
**Pull request by mareklinka**
Fixes the long-standing test issues with R# SDK.

### CODE REVIEW

**Review by pavolbelusko — APPROVED** [review]
Happy to see the tests working again. What is the rationale behind the change that fixed them? Just curious

**Comment by pavolbelusko** [comment]
Do we have AppVeyor subscription?

**Comment by mareklinka** [comment]
There were actually two reasons for the test failure:

1. The old one - when running the tests, every other test would fail. This indicates some kind of caching issue. I eventually figured out a way to work around this by dropping the source files from cache:

`project.GetSolution().GetPsiServices().Files.PsiFilesCache.Drop(psiSourceFile)`

I honestly have no idea why this works but it does.

2. The introduction of the build VS build watcher caused a dependency that cannot be fulfilled in test environment. I worked around this by introducing the 

`HideVsBuildWatcherComponent : IHideImplementation<VsBuildWatcher>`

component. This thing hides the `VsBuildWatcher` during test runs so the tests don't try to inject the DTE.

Regarding AppVeyor, that thing is free for open source projects.

**Comment by pavolbelusko** [comment]
Thanks a lot for the comments!

**Pull request merged**
