### PR TITLE
Feature/wave 11

### PR DESCRIPTION
**Pull request by mareklinka**
Update R# SDK to 2017.3.1

### CODE REVIEW

**Review by pavolbelusko — APPROVED** [review]

**Comment by mareklinka** [comment]
Should we put this into develop instead of master?

**Comment by pavolbelusko** [comment]
I suggest to release it.

**Comment by mareklinka** [comment]
Well yes, but we need to get those changes to develop as well. And merging from master to develop looks shady as hell.

**Comment by pavolbelusko** [comment]
I understand now. Merge to develop, then create release branch i'd say. Speaking of master, we've never used it so far. Do we want to start?

**Comment by mareklinka** [comment]
Nah, let's just use develop and be done with it. I'll make the changes.

**Pull request closed without merging**
