### PR TITLE
[WIP] Update to 2018.1

### LINKED ISSUE #25: Support for Resharper 2018
Hi, i really like the idea of AgentMulder, but i cant find it in the Extensions Tab.
Could it be that it does not get listed because its not compatible with Resharper 2018? (I have 2018.1)

### PR DESCRIPTION
**Pull request by matkoch**
Will fix #25

### CODE REVIEW

**Comment by matkoch** [comment]
@mareklinka @pavolbelusko were the tests working for you before? Otherwise I think the transition is finished.

**Comment by mareklinka** [comment]
No, the tests have been broken for quite a while now. Thanks for the PR, I'll check it when I have some time (might be over the weekend, though).

**Comment by mareklinka** [comment]
I took a look at the code. Good job moving everything to the new csproj format, it's much more readable now.

However, some project settings got lost along the way (such as the common out directory and launch settings for debugging the solution live).

I have a changeset fixing these details - would it be fine if I open a PR on your fork?

**Comment by matkoch** [comment]
@mareklinka please do :) One thing I've asked myself: do you need the separation between all the different DI containers?  To have them as dedicated projects? If possible, I'd probably merge them.

**Comment by matkoch** [comment]
Ready? :)

**Comment by mareklinka** [comment]
I will create a release branch and deploy the new version early tomorrow. A big thanks for the work you did!

**Pull request merged**
